# Generated by Django 3.2.11 on 2022-03-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Report_Per_Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_member', models.BooleanField(db_index=True)),
                ('receipts_quantity', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category_Report_Per_Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_member', models.BooleanField(db_index=True)),
                ('receipts_quantity', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('store_id', models.IntegerField(db_index=True)),
                ('chain_id', models.IntegerField(db_index=True)),
                ('category_id', models.IntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.IntegerField(db_index=True)),
                ('product_quantity', models.IntegerField()),
                ('receipts_quantity', models.IntegerField(default=0)),
                ('return_quantity', models.IntegerField()),
                ('coupon_quantity', models.IntegerField(default=0)),
                ('coupon_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('return_receipts_quantity', models.IntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('member_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_data', to='home.category_report_per_member')),
            ],
        ),
        migrations.CreateModel(
            name='cash_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('store_id', models.IntegerField(db_index=True)),
                ('chain_id', models.IntegerField(db_index=True)),
                ('cachier_id', models.IntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.IntegerField(db_index=True)),
                ('product_quantity', models.IntegerField()),
                ('receipts_quantity', models.IntegerField(default=0)),
                ('return_quantity', models.IntegerField()),
                ('coupon_quantity', models.IntegerField(default=0)),
                ('coupon_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('return_receipts_quantity', models.IntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('member_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_data', to='home.cash_report_per_member')),
            ],
        ),
    ]
