# Generated by Django 3.2.11 on 2022-03-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='store',
        ),
    ]
