# Generated by Django 3.2.11 on 2022-03-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('s2c_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=500)),
                ('store_name_en', models.CharField(max_length=500)),
                ('store_area', models.CharField(max_length=500)),
                ('store_domain', models.CharField(max_length=500)),
                ('store_grade_id', models.IntegerField()),
                ('store_logo', models.CharField(max_length=500)),
                ('store_adress', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
                ('store_longitude', models.CharField(max_length=500)),
                ('store_latitude', models.CharField(max_length=500)),
                ('opening_hour', models.CharField(max_length=500)),
                ('closure_hour', models.CharField(max_length=500)),
                ('store_ip', models.CharField(max_length=500)),
                ('store_is_open', models.IntegerField()),
                ('store_is_selfsupport', models.IntegerField()),
                ('shop_owner_id', models.IntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('tax_number', models.CharField(max_length=500)),
                ('company_id', models.IntegerField(db_index=True, unique=True)),
            ],
        ),
    ]
