# Generated by Django 3.2.11 on 2022-03-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_name_it',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='closure_hour',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='contact',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='opening_hour',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_adress',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_area',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_domain',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_grade_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_ip',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_is_open',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_is_selfsupport',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_latitude',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_logo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_longitude',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='tax_number',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
