# Generated by Django 3.2.11 on 2022-03-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220309_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='s2c_id',
            new_name='id',
        ),
    ]
