# Generated by Django 3.2.11 on 2022-03-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_store_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField(db_index=True, unique=True)),
                ('chain_name', models.CharField(max_length=500, null=True)),
                ('adress', models.CharField(max_length=500, null=True)),
                ('chain_mobile', models.CharField(max_length=500, null=True)),
                ('chain_telephone', models.CharField(max_length=500, null=True)),
                ('chain_opening_hours', models.CharField(max_length=500, null=True)),
                ('chain_close_hours', models.CharField(max_length=500, null=True)),
                ('chain_trafic_line', models.CharField(max_length=500, null=True)),
                ('chain_img', models.CharField(max_length=500, null=True)),
                ('chain_lng', models.CharField(max_length=500, null=True)),
                ('chain_lat', models.CharField(max_length=500, null=True)),
                ('approved', models.CharField(max_length=500, null=True)),
                ('fattura_format', models.CharField(max_length=500, null=True)),
                ('next_format_num', models.IntegerField(null=True)),
                ('chain_ip', models.CharField(max_length=500, null=True)),
                ('chain_district_id', models.IntegerField(db_index=True, unique=True)),
                ('chain_district_info', models.CharField(max_length=500, null=True)),
                ('shop_owner_id', models.IntegerField(db_index=True)),
                ('manager_id', models.IntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('cash_registers', models.IntegerField(null=True)),
                ('contact', models.CharField(max_length=500, null=True)),
                ('warehouse_id', models.IntegerField(db_index=True, null=True)),
                ('manager2_id', models.IntegerField(null=True)),
                ('manager3_id', models.IntegerField(null=True)),
                ('chain_code', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('zip_code', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('state_province', models.CharField(max_length=500, null=True)),
                ('country', models.CharField(max_length=500, null=True)),
                ('tax_number', models.CharField(max_length=500, null=True)),
                ('company_id', models.IntegerField(db_index=True, null=True)),
                ('has_member_point', models.IntegerField(null=True)),
                ('is_online', models.IntegerField(null=True)),
                ('all_products_online', models.IntegerField(null=True)),
            ],
        ),
    ]
