# Generated by Django 3.2.11 on 2022-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='chain_district_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
