# Generated by Django 3.2.11 on 2022-03-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_chain_chain_district_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='manager_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
