# Generated by Django 3.2.11 on 2022-03-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_chain_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cachier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=500, null=True)),
                ('last_name', models.CharField(max_length=500, null=True)),
                ('contact', models.CharField(max_length=500, null=True)),
                ('password', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField(default=True)),
                ('img_url', models.CharField(max_length=500, null=True)),
                ('img_name', models.CharField(max_length=500, null=True)),
                ('hidden', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(null=True)),
                ('chain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain', to='home.chain')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='home.store')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Methods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('member_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('TVA', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('chain_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('order_number', models.CharField(max_length=500, null=True)),
                ('card_number', models.IntegerField(db_index=True)),
                ('vip_point', models.IntegerField(db_index=True)),
                ('cart_data', models.TextField(max_length=500, null=True)),
                ('invoice', models.CharField(max_length=500, null=True)),
                ('order_payment_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('store_id', models.IntegerField(db_index=True)),
                ('operator', models.CharField(max_length=500, null=True)),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('online_order_number', models.CharField(max_length=500, null=True)),
                ('online_user_id', models.CharField(max_length=500, null=True)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('is_paid', models.IntegerField()),
                ('cachier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cachier', to='home.cachier')),
                ('payment_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_way', to='home.payment_methods')),
            ],
        ),
    ]
