# Generated by Django 3.2.11 on 2022-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220311_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachier',
            name='chain_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cachier',
            name='store_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cachier_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_method_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
