# Generated by Django 3.2.11 on 2022-03-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220311_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachier',
            name='contact',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cachier',
            name='img_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cachier',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
