# Generated by Django 3.2.11 on 2022-03-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20220314_1122'),
    ]

    operations = [
      
    ]
