# Generated by Django 3.2.11 on 2022-04-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20220328_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField(db_index=True)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_per_card', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('products_sold', models.IntegerField()),
                ('total_order', models.IntegerField()),
                ('sales_member', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_non_member', models.DecimalField(decimal_places=2, max_digits=12)),
                ('products_member', models.IntegerField()),
                ('products_non_member', models.IntegerField()),
                ('date', models.DateField(db_index=True)),
            ],
        )
       
    ]
